library(tidyverse)
library(dbplyr)
library(magrittr)
library(readxl)
library(ggplot2)

#importing data
retail <- read.csv("/Users/pauletterodriguez/Downloads/Final Project (Google)/R Project/retail_sales.csv")
print(retail)
summary(retail)

#removing dollar signs and converting to numeric for revenue column
retail$Total.Amount <- gsub("\\$","",retail$Total.Amount)
print(retail)
retail$Total.Amount <- as.numeric(retail$Total.Amount)
print(retail)

#removing dollar signs and converting to numeric for price column
retail$Price.per.Unit <- gsub("\\$", "", retail$Price.per.Unit)
print(retail)
retail$Price.per.Unit <- as.numeric(retail$Price.per.Unit)
print(retail)

#fixing spelling errors
retail <- mutate(retail, Product.Category = recode(.x=Product.Category, "Beautie"="Beauty"))
retail <- mutate(retail, Product.Category = recode(.x=Product.Category, "Beautyy"="Beauty"))
retail <- mutate(retail, Product.Category = recode(.x=Product.Category, "Clothi"="Clothing"))
retail <- mutate(retail, Product.Category = recode(.x=Product.Category, "Electronicss"="Electronics"))
retail <- mutate(retail, Product.Category = recode(.x=Product.Category, "Electronixc"="Electronics"))
print(retail)

# Question 1: What is the total revenue generated by each product category?
sum(retail$Total.Amount) #calculating total revenue of sales
mean(retail$Total.Amount) #calculating avg revenue per transaction

#calculating total revenue per product category type
total_revenue <- retail %>%
  group_by(Product.Category)%>%
  summarize(totalrevenue = sum(Total.Amount))
print(total_revenue)

#Bar Plot for total quantity sold per product category
ggplot(total_revenue, aes(x = Product.Category, y = totalrevenue)) +
  geom_bar(stat = "identity", fill = "#76D7C4") +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "Total Revenue by Product Category",
       x = "Product Category", y = "Revenue", 
       subtitle = "Electronics stands as the top-selling category, while Beauty ranks as the least sold") +
  theme(axis.text.x = element_text(size = 8, color = "#39858C", face = "bold")) +
  theme(plot.title = element_text(color = "#3498DB", face = "bold")) +
  theme(plot.subtitle = element_text(size = 8, color = "#5F75CE", face = "italic"))

#Question 2: What are the spending patterns by gender and age group?
#Categorizing Age into groups
retail$Age <- cut(retail$Age, breaks = c(18, 25, 35, 45, 55, 65, Inf), 
                     labels = c("18-25", "26-35", "36-45", "46-55", "56-65", "65+"), right = FALSE)

#purchasing patterns by age group
age_group_analysis <- retail %>%
  group_by(Age) %>%
  summarise(AverageSpend = mean(Total.Amount),
            TotalPurchases = n())

#Bar Plot of Age Group Analysis
ggplot(age_group_analysis, aes(x = Age, y = TotalPurchases)) +
  geom_bar(stat = "identity", fill = "#76D7C4") +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "Purchasing Patterns by Age Group",
       x = "Age", y = "Average Spend", 
       subtitle = "On average the older age groups purchase more than the younger age groups.") +
  theme(axis.text.x = element_text(size = 8, color = "#8c3985", face = "bold")) +
  theme(plot.title = element_text(color = "#3498DB", face = "bold")) +
  theme(plot.subtitle = element_text(size = 8, color = "#5F75CE", face = "italic"))

print(age_group_analysis)

#purchasing behavior by gender
gender_analysis <- retail %>%
  group_by(Gender) %>%
  summarise(AvgSpend = mean(Total.Amount),
            TotalPurchase = n())

print(gender_analysis)

#Bar Plot of Gender Analysis
ggplot(gender_analysis, aes(x = Gender, y = TotalPurchase)) +
  geom_bar(stat = "identity", fill = "#5F75CE") +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "Purchasing Patterns by Gender",
       x = "Gender", y = "Average Spend", 
       subtitle = "On average females spend more than males.") +
  theme(axis.text.x = element_text(size = 8, color = "#8c3985", face = "bold")) +
  theme(plot.title = element_text(color = "#3498DB", face = "bold")) +
  theme(plot.subtitle = element_text(size = 8, color = "#5F75CE", face = "italic"))

#Question 3: What is the average transaction amount by customer?
#calculate total transactions
trans <- length(retail$Transaction.ID)

#calculate total revenue
rev <- sum(retail$Total.Amount)

#calculate average transaction value 
avg_trans_val <- rev/trans
print(avg_trans_val)

#Question 4: Is there any seasonality or trend in the transactions based on the date?

new_data <- retail %>% mutate(month = format(as.Date(Date), "%m")) %>%
  mutate(year_number = format(as.Date(Date), "%Y"))
new_data <- new_data[order(new_data$Date), ]
print(new_data)

#create new column for purchase date to change it into first of the month
new_data$Purchase_Date <- paste(new_data$year_number, new_data$month, '01', sep = "-")
new_data$Purchase_Date <- as.Date(new_data$Purchase_Date)

#filter unfinished month transaction
new_data <- new_data %>% filter(Purchase_Date < as.Date("2023-09-01"))
new_data$month = as.numeric(new_data$month)
new_data$month <- cut(new_data$month, breaks = c(01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12, Inf), 
                  labels = c("Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"), right = FALSE)

summary(new_data$month)

date_analysis <- new_data %>%
  group_by(month) %>%
  summarise(#TotalQuantity = sum(Quantity))
            TRev = sum(Total.Amount))

plot(date_analysis, col='blue', pch=19, cex=2, main="Monthly Total Revenue",
     xlab="Months", ylab="Revenue")

head(n=12,date_analysis)

#Question 5: Which customers made the most purchases, and what is the frequency of their transactions?
retail$Customer.ID <- as.character(retail$Customer.ID)
retail[which.max(retail$Quantity),]$Customer.ID
retail[which.min(retail$Quantity),]$Customer.ID
